import { useState } from "react";
import type { DashboardPatientData } from "@/data/patientData";
import { ArrowLeft, FileText, Download, Copy, Check, Eye, RefreshCw } from "lucide-react";
import StructuredChartNote from "./StructuredChartNote";
import { apiFetch } from "@/lib/apiClient";
import { API_BASE } from "@/lib/processedDocuments";

interface ChartNoteDetailProps {
  onBack: () => void;
  data: DashboardPatientData;
  chartNoteContent: string;
  documentId: string;
}

const ChartNoteDetail = ({ onBack, data, chartNoteContent, documentId }: ChartNoteDetailProps) => {
  const [copied, setCopied] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [viewMode, setViewMode] = useState<"structured" | "raw">("structured");
  const [chartNoteData, setChartNoteData] = useState(chartNoteContent);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(chartNoteContent);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const handleRegenerate = async () => {
    setIsRegenerating(true);
    try {
      const response = await apiFetch(`${API_BASE}/documents/${documentId}/chart-note?regenerate=true`);

      if (!response.ok) {
        throw new Error("Failed to regenerate chart note");
      }

      const result = await response.json();
      setChartNoteData(result.chartNote.content);
    } catch (error) {
      console.error("Regeneration failed:", error);
      alert("Failed to regenerate chart note. Please try again.");
    } finally {
      setIsRegenerating(false);
    }
  };

  const handleExportPDF = async () => {
    setIsExporting(true);
    try {
      // Fetch the chart note PDF from the server
      const response = await apiFetch(`${API_BASE}/documents/${documentId}/chart-note/pdf`, {
        method: "POST",
        headers: { "Content-Type": "application/json" }
      });

      if (!response.ok) {
        throw new Error("Failed to generate PDF");
      }

      // Download the PDF
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `chart-note-${data.patient.mrn || documentId}-${new Date().toISOString().split("T")[0]}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);

    } catch (error) {
      console.error("Export failed:", error);
      // Fallback: open in new tab with print dialog
      const printWindow = window.open("", "_blank");
      if (printWindow) {
        printWindow.document.write(`
          <!DOCTYPE html>
          <html>
          <head>
            <title>Chart Note - ${data.patient.name}</title>
            <style>
              body { font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
              pre { white-space: pre-wrap; font-family: Arial, sans-serif; font-size: 14px; }
              .logos { display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #003087; }
              .logo { height: 50px; }
              .header { text-align: center; margin-bottom: 20px; }
              .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 12px; color: #666; }
            </style>
          </head>
          <body>
            <div class="logos">
              <img src="/manipal-logo.png" alt="Manipal Hospitals" class="logo" />
              <img src="/yavar-logo.png" alt="Powered by Yavar.ai" class="logo" style="height: 30px;" />
            </div>
            <pre>${chartNoteContent}</pre>
            <div class="footer">
              Generated by Yavar.ai Chart Note Generator<br />
              ${new Date().toLocaleString()}
            </div>
          </body>
          </html>
        `);
        printWindow.document.close();
      }
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <button onClick={onBack} className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to Dashboard
        </button>
        <div className="flex items-center gap-2">
          <button
            onClick={handleRegenerate}
            disabled={isRegenerating}
            className="flex items-center gap-2 px-4 py-2 text-sm border rounded-lg hover:bg-muted transition-colors disabled:opacity-50"
            title="Regenerate with ReAct AI Agent"
          >
            <RefreshCw className={`w-4 h-4 ${isRegenerating ? "animate-spin" : ""}`} />
            {isRegenerating ? "Regenerating..." : "Regenerate AI"}
          </button>
          <button
            onClick={() => setViewMode(viewMode === "structured" ? "raw" : "structured")}
            className="flex items-center gap-2 px-4 py-2 text-sm border rounded-lg hover:bg-muted transition-colors"
            title="Toggle view mode"
          >
            <Eye className="w-4 h-4" />
            {viewMode === "structured" ? "Raw View" : "Structured View"}
          </button>
          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-4 py-2 text-sm border rounded-lg hover:bg-muted transition-colors"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            {copied ? "Copied!" : "Copy"}
          </button>
          <button
            onClick={handleExportPDF}
            disabled={isExporting}
            className="flex items-center gap-2 px-4 py-2 text-sm bg-primary text-primary-foreground rounded-lg hover:opacity-90 transition-colors disabled:opacity-50"
          >
            <Download className="w-4 h-4" />
            {isExporting ? "Exporting..." : "Export PDF"}
          </button>
        </div>
      </div>

      {/* Header with logos */}
      <div className="flex items-center justify-between border-b pb-4">
        <div className="flex items-center gap-4">
          <img src="/manipal-logo.png" alt="Manipal Hospitals" className="h-8" />
        </div>
        <img src="/yavar-logo.png" alt="Powered by Yavar.ai" className="h-8 opacity-70" />
      </div>

      {/* Patient info banner */}
      <div className="bg-muted/30 rounded-lg p-4">
        <div className="flex flex-wrap gap-x-6 gap-y-2 text-sm">
          <div><span className="font-medium">Patient:</span> {data.patient.name}</div>
          <div><span className="font-medium">MRN:</span> {data.patient.mrn}</div>
          <div><span className="font-medium">Age/Gender:</span> {data.patient.age} {data.patient.gender}</div>
          <div><span className="font-medium">Admission:</span> {data.admission.admissionDate ? new Date(data.admission.admissionDate).toLocaleDateString() : "N/A"}</div>
        </div>
      </div>

      {/* Chart Note Content */}
      <div className="bg-card rounded-xl border p-8">
        <div className="flex items-center gap-3 mb-6">
          <FileText className="w-6 h-6 text-primary" />
          <h2 className="text-xl font-bold text-foreground">CLINICAL CHART NOTE</h2>
          <span className="ml-auto text-xs px-2 py-1 rounded-full bg-blue-100 text-blue-800">
            {viewMode === "structured" ? "Structured View" : "Raw Text"}
          </span>
        </div>

        {viewMode === "structured" ? (
          <StructuredChartNote data={data} chartNoteContent={chartNoteData} />
        ) : (
          <pre className="whitespace-pre-wrap font-serif text-sm leading-relaxed text-foreground">
            {chartNoteData}
          </pre>
        )}
      </div>

      {/* Footer with disclaimer */}
      <div className="text-center text-xs text-muted-foreground">
        <p>This chart note was automatically generated from the discharge summary document.</p>
        <p>Clinician review and signature required.</p>
        <p className="mt-2">Powered by Yavar.ai</p>
      </div>
    </div>
  );
};

export default ChartNoteDetail;
