import type { DashboardPatientData } from "@/data/patientData";

interface StructuredChartNoteProps {
  data: DashboardPatientData;
  chartNoteContent: string;
}

/**
 * Render LLM-generated chart note with proper SOAP format handling
 */
const StructuredChartNote = ({ data, chartNoteContent }: StructuredChartNoteProps) => {

  // Parse chart note into SOAP sections
  const parseSOAPSections = (content: string) => {
    const sections: { title: string; content: string; soapType: 'S' | 'O' | 'A' | 'P' | 'OTHER' }[] = [];
    const lines = content.split('\n');
    let currentSection: { title: string; content: string; soapType: 'S' | 'O' | 'A' | 'P' | 'OTHER' } | null = null;
    let currentContent: string[] = [];

    for (const line of lines) {
      const trimmed = line.trim();

      // Skip empty lines and separators
      if (!trimmed || trimmed === '---' || trimmed.startsWith('=')) continue;

      // Skip header/footer lines
      if (trimmed.includes('DISCHARGE SUMMARY CHART NOTE') && trimmed.length < 60) continue;
      if (trimmed.includes('Patient:') && trimmed.includes('MRN:')) continue;
      if (trimmed.includes('Admission:') && trimmed.includes('Discharge:')) continue;
      if (trimmed.includes('Generated:') || trimmed.includes('Generated by')) continue;
      if (trimmed.includes('Clinician review') || trimmed.includes('AI-generated')) continue;
      if (trimmed.includes('Validation Summary:')) continue;
      if (trimmed.includes('_________________________')) continue;

      // Detect section headers - look for SOAP indicators or ALL CAPS headers
      let soapType: 'S' | 'O' | 'A' | 'P' | 'OTHER' = 'OTHER';

      if (trimmed.toUpperCase().includes('SUBJECTIVE') || trimmed.toUpperCase().includes('(S)') ||
          trimmed.toUpperCase().includes('HISTORY') || trimmed.toUpperCase().includes('PRESENTATION')) {
        soapType = 'S';
      } else if (trimmed.toUpperCase().includes('OBJECTIVE') || trimmed.toUpperCase().includes('(O)') ||
                 trimmed.toUpperCase().includes('CLINICAL FINDINGS') || trimmed.toUpperCase().includes('VITAL')) {
        soapType = 'O';
      } else if (trimmed.toUpperCase().includes('ASSESSMENT') || trimmed.toUpperCase().includes('(A)') ||
                 trimmed.toUpperCase().includes('DIAGNOSIS') || trimmed.toUpperCase().includes('CLINICAL JUDGMENT')) {
        soapType = 'A';
      } else if (trimmed.toUpperCase().includes('PLAN') || trimmed.toUpperCase().includes('(P)') ||
                 trimmed.toUpperCase().includes('DISCHARGE PLAN') || trimmed.toUpperCase().includes('RECOMMENDATIONS')) {
        soapType = 'P';
      }

      // Check if this is a section header
      const isSectionHeader = (
        soapType !== 'OTHER' ||
        (trimmed === trimmed.toUpperCase() && trimmed.length > 3 && trimmed.length < 60)
      );

      if (isSectionHeader) {
        // Save previous section
        if (currentSection) {
          currentSection.content = currentContent.join('\n').trim();
          if (currentSection.content) {
            sections.push(currentSection);
          }
        }

        currentSection = {
          title: trimmed,
          content: '',
          soapType
        };
        currentContent = [];
      } else {
        currentContent.push(line);
      }
    }

    // Don't forget the last section
    if (currentSection) {
      currentSection.content = currentContent.join('\n').trim();
      if (currentSection.content) {
        sections.push(currentSection);
      }
    }

    return sections;
  };

  // Render content with proper formatting
  const renderContent = (content: string) => {
    const lines = content.split('\n').filter(l => l.trim());

    return lines.map((line, idx) => {
      const trimmed = line.trim();

      // Bullet points or dash lists
      if (trimmed.startsWith('-') || trimmed.startsWith('•') || trimmed.startsWith('*')) {
        return (
          <li key={idx} className="text-sm text-gray-700 mb-1 ml-5 list-disc">
            {trimmed.replace(/^[-•*]\s*/, '')}
          </li>
        );
      }

      // Bold/Colon lines (sub-headers)
      if (trimmed.includes(':') && trimmed.length < 100 && !trimmed.includes('http')) {
        const colonIndex = trimmed.indexOf(':');
        const label = trimmed.substring(0, colonIndex + 1);
        const value = trimmed.substring(colonIndex + 1).trim();

        return (
          <div key={idx} className="mb-2">
            <span className="font-semibold text-gray-900">{label}</span>
            {value && <span className="text-gray-700">{value}</span>}
          </div>
        );
      }

      // Regular text paragraph
      return (
        <p key={idx} className="text-sm text-gray-700 leading-relaxed mb-2">
          {trimmed}
        </p>
      );
    });
  };

  const getSOAPStyles = (soapType: 'S' | 'O' | 'A' | 'P' | 'OTHER') => {
    const styles = {
      S: {
        border: 'border-blue-400',
        bg: 'bg-blue-50/40',
        header: 'bg-blue-600',
        icon: 'S'
      },
      O: {
        border: 'border-purple-400',
        bg: 'bg-purple-50/40',
        header: 'bg-purple-600',
        icon: 'O'
      },
      A: {
        border: 'border-amber-400',
        bg: 'bg-amber-50/40',
        header: 'bg-amber-600',
        icon: 'A'
      },
      P: {
        border: 'border-green-400',
        bg: 'bg-green-50/40',
        header: 'bg-green-600',
        icon: 'P'
      },
      OTHER: {
        border: 'border-gray-400',
        bg: 'bg-gray-50/40',
        header: 'bg-gray-600',
        icon: ''
      }
    };
    return styles[soapType];
  };

  const sections = parseSOAPSections(chartNoteContent);

  return (
    <div className="font-sans text-gray-800">
      {/* Header */}
      <div className="text-center py-4 border-b-2 border-blue-800 bg-gradient-to-r from-blue-600 to-blue-800 -mx-8 px-8 -mt-8 mb-6 rounded-t-xl">
        <h1 className="text-xl font-bold text-white">CLINICAL CHART NOTE</h1>
        <p className="text-sm text-blue-100">SOAP Format</p>
      </div>

      {/* Patient Info Banner */}
      <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-xl border border-blue-200 overflow-hidden mb-6">
        <div className="bg-blue-600 px-4 py-2 flex items-center justify-between">
          <h3 className="text-sm font-semibold text-white uppercase tracking-wide">Patient Information</h3>
          <div className="flex gap-2">
            <span className="px-2 py-1 bg-blue-700 rounded text-xs text-white">S: Subjective</span>
            <span className="px-2 py-1 bg-purple-700 rounded text-xs text-white">O: Objective</span>
            <span className="px-2 py-1 bg-amber-700 rounded text-xs text-white">A: Assessment</span>
            <span className="px-2 py-1 bg-green-700 rounded text-xs text-white">P: Plan</span>
          </div>
        </div>
        <div className="p-4">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <div className="bg-white rounded-lg p-3 border border-blue-100">
              <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">Name</div>
              <div className="text-sm font-semibold text-gray-900">{data.patient.name}</div>
            </div>
            <div className="bg-white rounded-lg p-3 border border-blue-100">
              <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">MRN</div>
              <div className="text-sm font-semibold text-gray-900">{data.patient.mrn}</div>
            </div>
            <div className="bg-white rounded-lg p-3 border border-blue-100">
              <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">Age/Gender</div>
              <div className="text-sm font-semibold text-gray-900">{data.patient.age} {data.patient.gender}</div>
            </div>
            <div className="bg-white rounded-lg p-3 border border-blue-100">
              <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">Admission</div>
              <div className="text-sm font-semibold text-gray-900">
                {data.admission.admissionDate ? new Date(data.admission.admissionDate).toLocaleDateString() : 'N/A'}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* SOAP Sections */}
      <div className="space-y-5">
        {sections.map((section, index) => {
          const styles = getSOAPStyles(section.soapType);
          const cleanTitle = section.title
            .replace(/SUBJECTIVE|\(S\)/gi, '')
            .replace(/OBJECTIVE|\(O\)/gi, '')
            .replace(/ASSESSMENT|\(A\)/gi, '')
            .replace(/PLAN|\(P\)/gi, '')
            .replace(/[:\s]+$/, '')
            .trim();

          return (
            <div
              key={index}
              className={`rounded-lg border-l-4 ${styles.border} ${styles.bg} overflow-hidden shadow-sm`}
            >
              <div className={`${styles.header} px-4 py-2 flex items-center gap-3`}>
                {styles.icon && (
                  <span className="w-6 h-6 bg-white/20 rounded flex items-center justify-center text-xs font-bold">
                    {styles.icon}
                  </span>
                )}
                <h4 className="text-base font-bold text-white uppercase tracking-wide">
                  {cleanTitle || section.title}
                </h4>
              </div>
              <div className="p-4 bg-white">
                <ul className="space-y-1">
                  {renderContent(section.content)}
                </ul>
              </div>
            </div>
          );
        })}
      </div>

      {/* Footer */}
      <div className="mt-8 pt-4 border-t border-gray-300 text-center text-xs text-gray-500">
        <p>Generated by Yavar.ai | {new Date().toLocaleString()}</p>
        <p className="mt-1">This is an AI-generated document. Clinician review and signature required.</p>
      </div>
    </div>
  );
};

export default StructuredChartNote;
